//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oti.Sas.ContractDesigner.ContractService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/Oti.Sas.Models")]
    public enum Language : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Turkish = 1400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1401,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Russian = 1402,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Polish = 1403,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ukrainian = 1404,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Georgian = 1405,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractResponse", Namespace="http://schemas.datacontract.org/2004/07/Oti.Sas.Services.Russia.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ContractResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Oti.Sas.ContractDesigner.ContractService.Contract[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Oti.Sas.ContractDesigner.ContractService.Contract[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorInfo {
            get {
                return this.ErrorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoField, value) != true)) {
                    this.ErrorInfoField = value;
                    this.RaisePropertyChanged("ErrorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/Oti.Sas.Services.Russia.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContractService.IContractService")]
    public interface IContractService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.otiholding.com/Sas/2/1/0/1) of message LoginRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.otiholding.com/Sas/2/1/0/1/ISasServiceBase/Login", ReplyAction="http://www.otiholding.com/Sas/2/1/0/1/ISasServiceBase/LoginResponse")]
        Oti.Sas.ContractDesigner.ContractService.LoginResponse Login(Oti.Sas.ContractDesigner.ContractService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.otiholding.com/Sas/2/1/0/1/ISasServiceBase/Login", ReplyAction="http://www.otiholding.com/Sas/2/1/0/1/ISasServiceBase/LoginResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.LoginResponse> LoginAsync(Oti.Sas.ContractDesigner.ContractService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetContracts", ReplyAction="http://tempuri.org/IContractService/GetContractsResponse")]
        Oti.Sas.ContractDesigner.ContractService.ContractResponse GetContracts(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetContracts", ReplyAction="http://tempuri.org/IContractService/GetContractsResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> GetContractsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetContract", ReplyAction="http://tempuri.org/IContractService/GetContractResponse")]
        Oti.Sas.ContractDesigner.ContractService.ContractResponse GetContract(string token, int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetContract", ReplyAction="http://tempuri.org/IContractService/GetContractResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> GetContractAsync(string token, int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/SaveContract", ReplyAction="http://tempuri.org/IContractService/SaveContractResponse")]
        Oti.Sas.ContractDesigner.ContractService.ContractResponse SaveContract(string token, string userName, int templateId, byte[] content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/SaveContract", ReplyAction="http://tempuri.org/IContractService/SaveContractResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> SaveContractAsync(string token, string userName, int templateId, byte[] content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/Unlock", ReplyAction="http://tempuri.org/IContractService/UnlockResponse")]
        Oti.Sas.ContractDesigner.ContractService.ContractResponse Unlock(string token, int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/Unlock", ReplyAction="http://tempuri.org/IContractService/UnlockResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> UnlockAsync(string token, int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/Lock", ReplyAction="http://tempuri.org/IContractService/LockResponse")]
        Oti.Sas.ContractDesigner.ContractService.ContractResponse Lock(string token, int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/Lock", ReplyAction="http://tempuri.org/IContractService/LockResponse")]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> LockAsync(string token, int templateId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://www.otiholding.com/Sas/2/1/0/1", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.otiholding.com/Sas/2/1/0/1", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.otiholding.com/Sas/2/1/0/1", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.otiholding.com/Sas/2/1/0/1", Order=2)]
        public Oti.Sas.ContractDesigner.ContractService.Language language;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string userName, string password, Oti.Sas.ContractDesigner.ContractService.Language language) {
            this.userName = userName;
            this.password = password;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://www.otiholding.com/Sas/2/1/0/1", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.otiholding.com/Sas/2/1/0/1", Order=0)]
        public string LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractServiceChannel : Oti.Sas.ContractDesigner.ContractService.IContractService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractServiceClient : System.ServiceModel.ClientBase<Oti.Sas.ContractDesigner.ContractService.IContractService>, Oti.Sas.ContractDesigner.ContractService.IContractService {
        
        public ContractServiceClient() {
        }
        
        public ContractServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oti.Sas.ContractDesigner.ContractService.LoginResponse Oti.Sas.ContractDesigner.ContractService.IContractService.Login(Oti.Sas.ContractDesigner.ContractService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string userName, string password, Oti.Sas.ContractDesigner.ContractService.Language language) {
            Oti.Sas.ContractDesigner.ContractService.LoginRequest inValue = new Oti.Sas.ContractDesigner.ContractService.LoginRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.language = language;
            Oti.Sas.ContractDesigner.ContractService.LoginResponse retVal = ((Oti.Sas.ContractDesigner.ContractService.IContractService)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.LoginResponse> Oti.Sas.ContractDesigner.ContractService.IContractService.LoginAsync(Oti.Sas.ContractDesigner.ContractService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.LoginResponse> LoginAsync(string userName, string password, Oti.Sas.ContractDesigner.ContractService.Language language) {
            Oti.Sas.ContractDesigner.ContractService.LoginRequest inValue = new Oti.Sas.ContractDesigner.ContractService.LoginRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.language = language;
            return ((Oti.Sas.ContractDesigner.ContractService.IContractService)(this)).LoginAsync(inValue);
        }
        
        public Oti.Sas.ContractDesigner.ContractService.ContractResponse GetContracts(string token) {
            return base.Channel.GetContracts(token);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> GetContractsAsync(string token) {
            return base.Channel.GetContractsAsync(token);
        }
        
        public Oti.Sas.ContractDesigner.ContractService.ContractResponse GetContract(string token, int templateId) {
            return base.Channel.GetContract(token, templateId);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> GetContractAsync(string token, int templateId) {
            return base.Channel.GetContractAsync(token, templateId);
        }
        
        public Oti.Sas.ContractDesigner.ContractService.ContractResponse SaveContract(string token, string userName, int templateId, byte[] content) {
            return base.Channel.SaveContract(token, userName, templateId, content);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> SaveContractAsync(string token, string userName, int templateId, byte[] content) {
            return base.Channel.SaveContractAsync(token, userName, templateId, content);
        }
        
        public Oti.Sas.ContractDesigner.ContractService.ContractResponse Unlock(string token, int templateId) {
            return base.Channel.Unlock(token, templateId);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> UnlockAsync(string token, int templateId) {
            return base.Channel.UnlockAsync(token, templateId);
        }
        
        public Oti.Sas.ContractDesigner.ContractService.ContractResponse Lock(string token, int templateId) {
            return base.Channel.Lock(token, templateId);
        }
        
        public System.Threading.Tasks.Task<Oti.Sas.ContractDesigner.ContractService.ContractResponse> LockAsync(string token, int templateId) {
            return base.Channel.LockAsync(token, templateId);
        }
    }
}
